# config/routes.yaml


# Partie affichage
index:
    path: /
    controller: App\Controller\DefaultController::indexAction

logout:
    path: /logout

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\DefaultController::number

teams:
    path: /teams
    controller: App\Controller\TeamController::ListTeamConfAction

team:
    path: /teams/team/{id}
    controller: App\Controller\TeamController::findTeam

# Partie admin
admin:
    path: /admin
    controller: App\Controller\Admin\HomepageController::adminIndexAction

addTeam:
    path: /admin/addTeam
    controller: App\Controller\TeamController::addTeamAction

addTeamBDD:
    path: /admin/addTeamBDD
    controller: App\Controller\TeamController::addBDDTeamAction

addPost:
    path: /admin/addPost
    controller: App\Controller\Admin\PosteController::addPosteAction

addLegende:
    path: /admin/addLegende
    controller: App\Controller\Admin\JoueurController::addLegendeAction

addBDDLegende:
    path: /admin/BDDLegende
    controller: App\Controller\Admin\JoueurController::addBDDLegendeAction

addHistory:
    path: /admin/addHistory
    controller: App\Controller\Admin\HistoryController::addHistoryAction

addStadium:
    path: /admin/addStadium
    controller: App\Controller\Admin\StadiumController::addStadiumAction

addFait:
    path: /admin/addFait
    controller: App\Controller\Admin\FaitController::addFaitAction

addBDDFait:
    path: /admin/addBDDFait
    controller: App\Controller\Admin\FaitController::addBDDFaitAction

addConference:
    path: /admin/addConference
    controller: App\Controller\Admin\ConferenceController::addConferenceAction

addConferenceBDD:
    path: /admin/addConferenceBDD
    controller: App\Controller\Admin\ConferenceController::addBDDConferenceAction

addJoueur:
    path: /admin/addJoueur
    controller: App\Controller\Admin\JoueurController::addJoueurAction

addJoueurBDD:
    path: /admin/addJoueurBDD
    controller: App\Controller\Admin\JoueurController::addJoueurBDDAction



# Partie Membre
member:
    path: /member
    controller: App\Controller\Member\MemberController::memberIndexAction



